import { createHash } from "node:crypto";

const V04_GRAY_TEST_VIDEO_ID = "video_v04_gray_test_f79086fba2876352";
const V04_GRAY_TEST_OBJECT_KEY = `videos/${V04_GRAY_TEST_VIDEO_ID}/original`;

export function assertV04GrayTestMediaTarget(videoId: string, objectKey: string) {
  if (videoId !== V04_GRAY_TEST_VIDEO_ID
    || objectKey !== V04_GRAY_TEST_OBJECT_KEY
    || objectKey !== `videos/${videoId}/original`) {
    throw new Error("V04_GRAY_TEST_MEDIA_TARGET_INVALID");
  }
}

export const V04_GRAY_TEST_MEDIA = {
  schemaVersion: "V04_GRAY_TEST_MEDIA_V2",
  contentType: "video/mp4",
  originalName: "hamark-v04-gray-test-clip.mp4",
  title: "V0.4 灰度 TEST_ONLY 测试片",
  brand: "Hamark TEST_ONLY",
  description: "本项目本机生成的 1 秒无敏感测试片；仅用于 V0.4 小范围灰度验证。",
  fileSize: 1685,
  sha256: "f79086fba2876352cc38b4566da616b1e96518cddcbd6cfbb7b5dee295fd9181",
  videoId: V04_GRAY_TEST_VIDEO_ID,
  testRunId: "V04_GRAY_PRODUCTION_GATE2_V1",
  objectKey: V04_GRAY_TEST_OBJECT_KEY,
} as const;

assertV04GrayTestMediaTarget(V04_GRAY_TEST_MEDIA.videoId, V04_GRAY_TEST_MEDIA.objectKey);

// Generated locally with /opt/homebrew/bin/ffmpeg from a one-second solid colour
// frame without audio. The bytes are frozen so the controlled operation can never
// upload an administrator-selected business or personal file by mistake.
const APPROVED_MEDIA_BASE64 = [
  "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAOFbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAA+gAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAkR0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAA+gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAKAAAABaAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAPoAAAAAAABAAAAAAG8bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAABAAAAAQABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAABZ21pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAASdzdGJsAAAAw3N0c2QAAAAAAAAAAQAAALNhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAKAAWgBIAAAASAAAAAAAAAABFUxhdmM2Mi4yOC4xMDIgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAAOWF2Y0MBZAAM/+EAG2dkAAyscgRCjfkwEQAAAwABAAADAAIPFCmEYAEAB2joQ4E0siz9+PgAAAAAEHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAAFwAAAAAAAAAAGHN0dHMAAAAAAAAAAQAAAAEAAEAAAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAABAAAAAQAAABRzdHN6AAAAAAAAAuAAAAABAAAAFHN0Y28AAAAAAAAAAQAAA7UAAADNdWR0YQAAAMVtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABtZGlyYXBwbAAAAAAAAAAAAAAAAJhpbHN0AAAALaluYW0AAAAlZGF0YQAAAAEAAAAASGFtYXJrIFYwLjQgVEVTVF9PTkxZAAAAJal0b28AAAAdZGF0YQAAAAEAAAAATGF2ZjYyLjEyLjEwMgAAAD6pY210AAAANmRhdGEAAAABAAAAAEdlbmVyYXRlZCBsb2NhbGx5OyBubyBidXNpbmVzcyBjb250ZW50AAAACGZyZWUAAALobWRhdAAAAq8GBf//q9xF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjUgcjMyMjIgYjM1NjA1YSAtIEguMjY0L01QRUctNCBBVkMgY29kZWMgLSBDb3B5bGVmdCAyMDAzLTIwMjUgLSBodHRwOi8vd3d3LnZpZGVvbGFuLm9yZy94MjY0Lmh0bWwgLSBvcHRpb25zOiBjYWJhYz0xIHJlZj0xNiBkZWJsb2NrPTE6MDowIGFuYWx5c2U9MHgzOjB4MTMzIG1lPXVtaCBzdWJtZT0xMCBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTI0IGNocm9tYV9tZT0xIHRyZWxsaXM9MiA4eDhkY3Q9MSBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTMgbG9va2FoZWFkX3RocmVhZHM9MSBzbGljZWRfdGhyZWFkcz0wIG5yPTAgZGVjaW1hdGU9MSBpbnRlcmxhY2VkPTAgYmx1cmF5X2NvbXBhdD0wIGNvbnN0cmFpbmVkX2ludHJhPTAgYmZyYW1lcz04IGJfcHlyYW1pZD0yIGJfYWRhcHQ9MiBiX2JpYXM9MCBkaXJlY3Q9MyB3ZWlnaHRiPTEgb3Blbl9nb3A9MCB3ZWlnaHRwPTIga2V5aW50PTI1MCBrZXlpbnRfbWluPTEgc2NlbmVjdXQ9NDAgaW50cmFfcmVmcmVzaD0wIHJjX2xvb2thaGVhZD02MCByYz1jcmYgbWJ0cmVlPTEgY3JmPTQ1LjAgcWNvbXA9MC42MCBxcG1pbj0wIHFwbWF4PTY5IHFwc3RlcD00IGlwX3JhdGlvPTEuNDAgYXE9MToxLjAwAIAAAAApZYiBAAK//ggnmWNEeF1RcqnjfO3MBxLGPuxQo25h1UuSCAIgAGGFm3k=",
].join("");

let approvedBytes: Uint8Array | null = null;

export function v04GrayTestMediaBytes() {
  assertV04GrayTestMediaTarget(V04_GRAY_TEST_MEDIA.videoId, V04_GRAY_TEST_MEDIA.objectKey);
  if (!approvedBytes) approvedBytes = new Uint8Array(Buffer.from(APPROVED_MEDIA_BASE64, "base64"));
  const digest = createHash("sha256").update(approvedBytes).digest("hex");
  if (approvedBytes.byteLength !== V04_GRAY_TEST_MEDIA.fileSize || digest !== V04_GRAY_TEST_MEDIA.sha256) {
    throw new Error("V04_GRAY_TEST_MEDIA_INTEGRITY_FAILED");
  }
  return approvedBytes.slice();
}
