import { getDbClient } from "./index";

const statements = [
  `CREATE TABLE IF NOT EXISTS app_admins (
    display_name TEXT PRIMARY KEY,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `INSERT INTO app_admins (display_name) VALUES
    ('老孙'),
    ('李丽萍'),
    ('晏恩华')
    ON CONFLICT (display_name) DO NOTHING`,
  `CREATE TABLE IF NOT EXISTS videos (
    id TEXT PRIMARY KEY,
    domain_key TEXT NOT NULL DEFAULT 'AD_VIDEO',
    title TEXT NOT NULL,
    brand TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    tags_json TEXT NOT NULL DEFAULT '[]',
    object_key TEXT NOT NULL,
    thumbnail_key TEXT,
    original_name TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'application/octet-stream',
    file_size INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'UPLOADING',
    rights_confirmed INTEGER NOT NULL DEFAULT 0,
    created_by_email TEXT NOT NULL,
    created_by_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
  )`,
  `ALTER TABLE videos ADD COLUMN IF NOT EXISTS thumbnail_key TEXT`,
  `ALTER TABLE videos ADD COLUMN IF NOT EXISTS data_scope TEXT NOT NULL DEFAULT 'BUSINESS'`,
  `ALTER TABLE videos ADD COLUMN IF NOT EXISTS test_run_id TEXT`,
  `CREATE INDEX IF NOT EXISTS videos_data_scope_idx ON videos(data_scope, created_at)`,
  `CREATE INDEX IF NOT EXISTS videos_status_idx ON videos(status)`,
  `CREATE INDEX IF NOT EXISTS videos_created_at_idx ON videos(created_at)`,
  `CREATE TABLE IF NOT EXISTS annotations (
    id TEXT PRIMARY KEY,
    video_id TEXT NOT NULL REFERENCES videos(id),
    author_email TEXT NOT NULL,
    author_name TEXT NOT NULL,
    taxonomy_version TEXT NOT NULL DEFAULT 'V0.2',
    status TEXT NOT NULL DEFAULT 'DRAFT',
    revision INTEGER NOT NULL DEFAULT 0,
    analysis_title TEXT NOT NULL DEFAULT '',
    commercial_intent TEXT NOT NULL DEFAULT '',
    creative_theme TEXT NOT NULL DEFAULT '',
    synopsis TEXT NOT NULL DEFAULT '',
    thinking_chain TEXT NOT NULL DEFAULT '',
    shot_commentary TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TEXT,
    deleted_at TEXT
  )`,
  `ALTER TABLE annotations ADD COLUMN IF NOT EXISTS workflow_version TEXT NOT NULL DEFAULT 'REVERSE-WORKFLOW-V0.2'`,
  `ALTER TABLE annotations ADD COLUMN IF NOT EXISTS source_snapshot_id TEXT`,
  `DROP INDEX IF EXISTS annotations_video_author_idx`,
  `CREATE UNIQUE INDEX IF NOT EXISTS annotations_video_author_taxonomy_idx ON annotations(video_id, author_email, taxonomy_version)`,
  `CREATE INDEX IF NOT EXISTS annotations_video_status_idx ON annotations(video_id, status)`,
  `CREATE TABLE IF NOT EXISTS annotation_taxonomy_versions (
    taxonomy_version TEXT PRIMARY KEY,
    workflow_version TEXT NOT NULL,
    status TEXT NOT NULL,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `INSERT INTO annotation_taxonomy_versions (
    taxonomy_version, workflow_version, status, label
  ) VALUES
    ('V0.2', 'REVERSE-WORKFLOW-V0.2', 'ACTIVE', '原19项标注体系 V0.2'),
    ('V0.3-PILOT', 'REVERSE-WORKFLOW-V0.3-PILOT', 'PILOT', '人机工作流 V0.3-PILOT')
    ON CONFLICT (taxonomy_version) DO NOTHING`,
  `CREATE TABLE IF NOT EXISTS shot_groups (
    id TEXT PRIMARY KEY,
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    order_index INTEGER NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    primary_role_id TEXT NOT NULL DEFAULT '',
    primary_role_name_snapshot TEXT NOT NULL DEFAULT '',
    auxiliary_roles_json TEXT NOT NULL DEFAULT '[]',
    custom_role TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    taxonomy_version TEXT NOT NULL DEFAULT 'V0.3-PILOT',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS shot_groups_annotation_order_idx ON shot_groups(annotation_id, order_index)`,
  `CREATE TABLE IF NOT EXISTS shots (
    id TEXT PRIMARY KEY,
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    order_index INTEGER NOT NULL,
    group_name TEXT NOT NULL DEFAULT '',
    shot_number TEXT NOT NULL DEFAULT '',
    start_time TEXT NOT NULL DEFAULT '',
    end_time TEXT NOT NULL DEFAULT '',
    shot_size TEXT NOT NULL DEFAULT '',
    camera_angle TEXT NOT NULL DEFAULT '',
    camera_movement TEXT NOT NULL DEFAULT '',
    visual_content TEXT NOT NULL DEFAULT '',
    dialogue TEXT NOT NULL DEFAULT '',
    voiceover TEXT NOT NULL DEFAULT '',
    screen_text TEXT NOT NULL DEFAULT '',
    sound_effect TEXT NOT NULL DEFAULT '',
    music TEXT NOT NULL DEFAULT '',
    creative_comment TEXT NOT NULL DEFAULT '',
    shot_group_id TEXT REFERENCES shot_groups(id)
  )`,
  `ALTER TABLE shots ADD COLUMN IF NOT EXISTS shot_group_id TEXT REFERENCES shot_groups(id)`,
  `CREATE INDEX IF NOT EXISTS shots_annotation_order_idx ON shots(annotation_id, order_index)`,
  `CREATE TABLE IF NOT EXISTS field_answers (
    id TEXT PRIMARY KEY,
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    field_code TEXT NOT NULL,
    answer TEXT NOT NULL DEFAULT '',
    evidence TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'HUMAN_ORIGINAL'
  )`,
  `ALTER TABLE field_answers ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'HUMAN_ORIGINAL'`,
  `CREATE UNIQUE INDEX IF NOT EXISTS field_answers_annotation_code_idx ON field_answers(annotation_id, field_code)`,
  `CREATE TABLE IF NOT EXISTS annotation_creative_structures (
    annotation_id TEXT PRIMARY KEY REFERENCES annotations(id),
    creative_button TEXT NOT NULL DEFAULT '',
    mechanism_statement TEXT NOT NULL DEFAULT '',
    mechanism_primary TEXT NOT NULL DEFAULT '',
    mechanism_auxiliary_json TEXT NOT NULL DEFAULT '[]',
    mechanism_custom TEXT NOT NULL DEFAULT '',
    realization_skeleton TEXT NOT NULL DEFAULT '',
    brand_product_landing TEXT NOT NULL DEFAULT '',
    story_reference_type TEXT NOT NULL DEFAULT '',
    story_archetype TEXT NOT NULL DEFAULT '',
    primary_creative_path TEXT NOT NULL DEFAULT '',
    auxiliary_creative_paths_json TEXT NOT NULL DEFAULT '[]',
    composite_state_reason TEXT NOT NULL DEFAULT '',
    formation_primary TEXT NOT NULL DEFAULT '',
    formation_auxiliary_json TEXT NOT NULL DEFAULT '[]',
    formation_statement TEXT NOT NULL DEFAULT '',
    formation_related_group_ids_json TEXT NOT NULL DEFAULT '[]',
    creative_carriers TEXT NOT NULL DEFAULT '',
    establishment_conditions TEXT NOT NULL DEFAULT '',
    strength_sources TEXT NOT NULL DEFAULT '',
    acceptance_contract TEXT NOT NULL DEFAULT '',
    audiovisual_mechanism TEXT NOT NULL DEFAULT '',
    information_release_turning TEXT NOT NULL DEFAULT '',
    creative_grade TEXT NOT NULL DEFAULT '',
    creative_grade_reason TEXT NOT NULL DEFAULT '',
    creative_grade_version TEXT NOT NULL DEFAULT 'CREATIVE-GRADE-V0.1',
    main_path_payload_json TEXT NOT NULL DEFAULT '{}',
    auxiliary_path_notes_json TEXT NOT NULL DEFAULT '{}',
    condition_flags_json TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `ALTER TABLE annotation_creative_structures ADD COLUMN IF NOT EXISTS condition_flags_json TEXT NOT NULL DEFAULT '{}'`,
  `CREATE TABLE IF NOT EXISTS annotation_snapshots (
    id TEXT PRIMARY KEY,
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    video_id TEXT NOT NULL REFERENCES videos(id),
    author_email TEXT NOT NULL,
    author_name TEXT NOT NULL,
    taxonomy_version TEXT NOT NULL,
    revision INTEGER NOT NULL,
    payload_json TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS annotation_snapshots_video_idx ON annotation_snapshots(video_id, created_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS annotation_snapshots_annotation_revision_idx ON annotation_snapshots(annotation_id, revision)`,
  `CREATE TABLE IF NOT EXISTS assignment_reviews (
    id TEXT PRIMARY KEY,
    submission_id TEXT NOT NULL REFERENCES annotation_snapshots(id),
    video_id TEXT NOT NULL REFERENCES videos(id),
    submission_revision INTEGER NOT NULL,
    grader_email TEXT NOT NULL,
    grader_name TEXT NOT NULL,
    grader_role TEXT NOT NULL DEFAULT 'PEER',
    rubric_version TEXT NOT NULL DEFAULT 'RUBRIC-V0.4',
    status TEXT NOT NULL DEFAULT 'DRAFT',
    revision INTEGER NOT NULL DEFAULT 0,
    scores_json TEXT NOT NULL DEFAULT '{}',
    total_score REAL NOT NULL DEFAULT 0,
    general_comment TEXT NOT NULL DEFAULT '',
    discussion_nomination INTEGER NOT NULL DEFAULT 0,
    is_valid_for_aggregate INTEGER NOT NULL DEFAULT 1,
    weight REAL NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TEXT,
    deleted_at TEXT
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS assignment_reviews_submission_grader_idx ON assignment_reviews(submission_id, grader_email)`,
  `CREATE INDEX IF NOT EXISTS assignment_reviews_submission_status_idx ON assignment_reviews(submission_id, status)`,
  `CREATE TABLE IF NOT EXISTS assignment_review_snapshots (
    id TEXT PRIMARY KEY,
    review_id TEXT NOT NULL REFERENCES assignment_reviews(id),
    submission_id TEXT NOT NULL REFERENCES annotation_snapshots(id),
    grader_email TEXT NOT NULL,
    rubric_version TEXT NOT NULL,
    revision INTEGER NOT NULL,
    payload_json TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS assignment_review_snapshots_revision_idx ON assignment_review_snapshots(review_id, revision)`,
  `CREATE INDEX IF NOT EXISTS assignment_review_snapshots_submission_idx ON assignment_review_snapshots(submission_id)`,
  `CREATE TABLE IF NOT EXISTS analysis_comments (
    id TEXT PRIMARY KEY,
    submission_id TEXT NOT NULL REFERENCES annotation_snapshots(id),
    video_id TEXT NOT NULL REFERENCES videos(id),
    parent_id TEXT REFERENCES analysis_comments(id),
    author_email TEXT NOT NULL,
    author_name TEXT NOT NULL,
    target_key TEXT NOT NULL,
    target_label TEXT NOT NULL DEFAULT '',
    selected_text TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'COMMENT',
    status TEXT NOT NULL DEFAULT 'OPEN',
    is_excellent INTEGER NOT NULL DEFAULT 0,
    marked_by_email TEXT,
    marked_by_name TEXT,
    marked_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TEXT,
    deleted_at TEXT,
    CHECK (kind IN ('COMMENT', 'EXPERT_NOTE')),
    CHECK (status IN ('OPEN', 'RESOLVED'))
  )`,
  `CREATE INDEX IF NOT EXISTS analysis_comments_submission_idx ON analysis_comments(submission_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS analysis_comments_parent_idx ON analysis_comments(parent_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS analysis_comments_target_idx ON analysis_comments(submission_id, target_key)`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS anchor_start INTEGER NOT NULL DEFAULT -1`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS anchor_end INTEGER NOT NULL DEFAULT -1`,
  `CREATE TABLE IF NOT EXISTS analysis_revision_suggestions (
    id TEXT PRIMARY KEY,
    submission_id TEXT NOT NULL REFERENCES annotation_snapshots(id),
    video_id TEXT NOT NULL REFERENCES videos(id),
    author_email TEXT NOT NULL,
    author_name TEXT NOT NULL,
    target_key TEXT NOT NULL,
    target_label TEXT NOT NULL DEFAULT '',
    selected_text TEXT NOT NULL DEFAULT '',
    anchor_start INTEGER NOT NULL DEFAULT 0,
    anchor_end INTEGER NOT NULL DEFAULT 0,
    replacement_text TEXT NOT NULL DEFAULT '',
    reason TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'PENDING',
    decided_by_email TEXT,
    decided_by_name TEXT,
    decided_at TEXT,
    applied_revision INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT,
    CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
  )`,
  `CREATE INDEX IF NOT EXISTS analysis_revision_suggestions_submission_idx
    ON analysis_revision_suggestions(submission_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS analysis_revision_suggestions_target_idx
    ON analysis_revision_suggestions(submission_id, target_key)`,
  `ALTER TABLE annotations ADD COLUMN IF NOT EXISTS review_status TEXT NOT NULL DEFAULT 'DRAFT'`,
  `ALTER TABLE annotations ADD COLUMN IF NOT EXISTS active_base_snapshot_id TEXT REFERENCES annotation_snapshots(id)`,
  `ALTER TABLE annotations ADD COLUMN IF NOT EXISTS base_snapshot_id TEXT REFERENCES annotation_snapshots(id)`,
  `ALTER TABLE annotations ADD COLUMN IF NOT EXISTS source_public_snapshot_id TEXT REFERENCES annotation_snapshots(id)`,
  `ALTER TABLE annotation_snapshots ADD COLUMN IF NOT EXISTS base_snapshot_id TEXT REFERENCES annotation_snapshots(id)`,
  `ALTER TABLE annotation_snapshots ADD COLUMN IF NOT EXISTS version_number INTEGER`,
  `ALTER TABLE annotation_snapshots ADD COLUMN IF NOT EXISTS revision_cause TEXT NOT NULL DEFAULT 'INITIAL'`,
  `ALTER TABLE annotation_snapshots ADD COLUMN IF NOT EXISTS workflow_status TEXT NOT NULL DEFAULT 'SUBMITTED'`,
  `ALTER TABLE annotation_snapshots ADD COLUMN IF NOT EXISTS submitted_at TEXT`,
  `ALTER TABLE annotation_snapshots ADD COLUMN IF NOT EXISTS source_public_snapshot_id TEXT REFERENCES annotation_snapshots(id)`,
  `CREATE TABLE IF NOT EXISTS analysis_review_rounds (
    id TEXT PRIMARY KEY,
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    video_id TEXT NOT NULL REFERENCES videos(id),
    submitted_snapshot_id TEXT NOT NULL REFERENCES annotation_snapshots(id),
    round_number INTEGER NOT NULL,
    reviewer_email TEXT,
    reviewer_name TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    decision_note TEXT,
    decided_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (status IN ('PENDING', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED')),
    UNIQUE (annotation_id, round_number),
    UNIQUE (submitted_snapshot_id)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS analysis_review_rounds_one_active_idx
    ON analysis_review_rounds(annotation_id)
    WHERE status IN ('PENDING', 'IN_REVIEW')`,
  `CREATE INDEX IF NOT EXISTS analysis_review_rounds_snapshot_idx
    ON analysis_review_rounds(submitted_snapshot_id)`,
  `CREATE TABLE IF NOT EXISTS analysis_revision_events (
    id TEXT PRIMARY KEY,
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    video_id TEXT NOT NULL REFERENCES videos(id),
    review_round_id TEXT NOT NULL REFERENCES analysis_review_rounds(id),
    base_snapshot_id TEXT NOT NULL REFERENCES annotation_snapshots(id),
    target_key TEXT NOT NULL,
    target_label TEXT NOT NULL DEFAULT '',
    edit_type TEXT NOT NULL,
    anchor_start INTEGER NOT NULL,
    anchor_end INTEGER NOT NULL,
    original_text TEXT NOT NULL,
    original_text_hash TEXT NOT NULL,
    replacement_text TEXT NOT NULL DEFAULT '',
    reason TEXT,
    actor_email TEXT NOT NULL,
    actor_name TEXT NOT NULL,
    actor_role TEXT NOT NULL,
    source TEXT NOT NULL,
    linked_comment_id TEXT REFERENCES analysis_comments(id),
    status TEXT NOT NULL DEFAULT 'DRAFT',
    applied_revision INTEGER,
    materialized_snapshot_id TEXT REFERENCES annotation_snapshots(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (edit_type IN ('RANGE_REPLACE', 'UNIT_REPLACE', 'INSERT', 'DELETE')),
    CHECK (actor_role IN ('AUTHOR', 'FINAL_REVIEWER')),
    CHECK (source IN ('SELF_REVISION', 'COMMENT_RESPONSE', 'FINAL_DIRECT_REVISION')),
    CHECK (status IN ('DRAFT', 'APPLIED', 'SUPERSEDED'))
  )`,
  `CREATE INDEX IF NOT EXISTS analysis_revision_events_round_idx
    ON analysis_revision_events(review_round_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS analysis_revision_events_target_idx
    ON analysis_revision_events(base_snapshot_id, target_key, created_at)`,
  `ALTER TABLE annotation_creative_structures ADD COLUMN IF NOT EXISTS vocabulary_version TEXT NOT NULL DEFAULT 'V0.3.1'`,
  `ALTER TABLE analysis_revision_events ADD COLUMN IF NOT EXISTS value_type TEXT NOT NULL DEFAULT 'TEXT'`,
  `ALTER TABLE analysis_revision_events ADD COLUMN IF NOT EXISTS original_value_json TEXT`,
  `ALTER TABLE analysis_revision_events ADD COLUMN IF NOT EXISTS replacement_value_json TEXT`,
  `ALTER TABLE analysis_revision_events ADD COLUMN IF NOT EXISTS vocabulary_version TEXT NOT NULL DEFAULT 'V0.3.1'`,
  `ALTER TABLE analysis_revision_events ADD COLUMN IF NOT EXISTS change_set_id TEXT`,
  `CREATE INDEX IF NOT EXISTS analysis_revision_events_value_type_idx
    ON analysis_revision_events(review_round_id, value_type, created_at)`,
  `CREATE INDEX IF NOT EXISTS analysis_revision_events_change_set_idx
    ON analysis_revision_events(review_round_id, change_set_id, created_at)`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS review_round_id TEXT REFERENCES analysis_review_rounds(id)`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS base_version_id TEXT REFERENCES annotation_snapshots(id)`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS workflow_status TEXT NOT NULL DEFAULT 'OPEN'`,
  `UPDATE analysis_comments SET workflow_status = 'RESOLVED'
    WHERE status = 'RESOLVED' AND workflow_status = 'OPEN'`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS resolved_by_email TEXT`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS resolved_by_name TEXT`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS final_conclusion TEXT`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS linked_revision_event_id TEXT REFERENCES analysis_revision_events(id)`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS handled_in_snapshot_id TEXT REFERENCES annotation_snapshots(id)`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS reopened_at TEXT`,
  `CREATE INDEX IF NOT EXISTS analysis_comments_review_round_idx
    ON analysis_comments(review_round_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS approved_analysis_releases (
    id TEXT PRIMARY KEY,
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    video_id TEXT NOT NULL REFERENCES videos(id),
    release_number INTEGER NOT NULL,
    approved_snapshot_id TEXT NOT NULL REFERENCES annotation_snapshots(id),
    source_snapshot_id TEXT NOT NULL REFERENCES annotation_snapshots(id),
    source_review_round_id TEXT NOT NULL REFERENCES analysis_review_rounds(id),
    payload_json TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    approved_by_email TEXT NOT NULL,
    approved_by_name TEXT NOT NULL,
    approved_at TEXT NOT NULL,
    expert_creative_grade TEXT NOT NULL,
    assignment_quality_grade TEXT,
    assignment_quality_version TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    replaces_release_id TEXT REFERENCES approved_analysis_releases(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (expert_creative_grade IN ('S', 'A', 'B', 'C')),
    CHECK (status IN ('ACTIVE', 'SUPERSEDED', 'WITHDRAWN')),
    UNIQUE (annotation_id, release_number)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS approved_analysis_releases_one_active_idx
    ON approved_analysis_releases(annotation_id)
    WHERE status = 'ACTIVE'`,
  `CREATE INDEX IF NOT EXISTS approved_analysis_releases_video_idx
    ON approved_analysis_releases(video_id, status, approved_at)`,
  `ALTER TABLE annotations ADD COLUMN IF NOT EXISTS base_release_id TEXT REFERENCES approved_analysis_releases(id)`,
  `ALTER TABLE annotation_snapshots ADD COLUMN IF NOT EXISTS base_release_id TEXT REFERENCES approved_analysis_releases(id)`,
  `ALTER TABLE annotation_snapshots ADD COLUMN IF NOT EXISTS snapshot_kind TEXT NOT NULL DEFAULT 'SUBMISSION'`,
  `CREATE TABLE IF NOT EXISTS v03_collaboration_streams (
    id TEXT PRIMARY KEY,
    video_id TEXT NOT NULL REFERENCES videos(id),
    taxonomy_version TEXT NOT NULL DEFAULT 'V0.3-PILOT',
    canonical_annotation_id TEXT NOT NULL REFERENCES annotations(id),
    initial_baseline_id TEXT,
    active_round_id TEXT,
    active_release_id TEXT REFERENCES approved_analysis_releases(id),
    current_snapshot_id TEXT REFERENCES annotation_snapshots(id),
    source_author_email TEXT NOT NULL,
    source_author_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_by_email TEXT NOT NULL,
    created_by_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (taxonomy_version = 'V0.3-PILOT'),
    CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    UNIQUE (video_id, taxonomy_version),
    UNIQUE (canonical_annotation_id)
  )`,
  `CREATE TABLE IF NOT EXISTS v03_collaboration_sources (
    id TEXT PRIMARY KEY,
    stream_id TEXT NOT NULL REFERENCES v03_collaboration_streams(id),
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    relation_type TEXT NOT NULL,
    source_author_email TEXT NOT NULL,
    source_author_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (relation_type IN ('CANONICAL', 'LEGACY_CONTRIBUTOR', 'MAPPED_SOURCE')),
    UNIQUE (stream_id, annotation_id)
  )`,
  `CREATE TABLE IF NOT EXISTS v03_collaboration_baselines (
    id TEXT PRIMARY KEY,
    stream_id TEXT NOT NULL REFERENCES v03_collaboration_streams(id),
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    source_type TEXT NOT NULL,
    source_snapshot_id TEXT REFERENCES annotation_snapshots(id),
    source_operation_key TEXT,
    payload_json JSONB NOT NULL,
    content_hash TEXT NOT NULL,
    source_author_email TEXT NOT NULL,
    source_author_name TEXT NOT NULL,
    created_by_email TEXT NOT NULL,
    created_by_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (source_type IN ('V02_MAPPED', 'EXISTING_V03', 'APPROVED_RELEASE')),
    UNIQUE (stream_id)
  )`,
  `CREATE TABLE IF NOT EXISTS v03_collaboration_rounds (
    id TEXT PRIMARY KEY,
    stream_id TEXT NOT NULL REFERENCES v03_collaboration_streams(id),
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    round_number INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    base_type TEXT NOT NULL,
    base_baseline_id TEXT REFERENCES v03_collaboration_baselines(id),
    base_release_id TEXT REFERENCES approved_analysis_releases(id),
    base_snapshot_id TEXT REFERENCES annotation_snapshots(id),
    starting_revision INTEGER NOT NULL,
    candidate_snapshot_id TEXT REFERENCES annotation_snapshots(id),
    created_by_email TEXT NOT NULL,
    created_by_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_by_email TEXT,
    ended_by_name TEXT,
    ended_at TEXT,
    CHECK (status IN ('ACTIVE', 'FINALIZED', 'SUPERSEDED', 'SOFT_DELETED')),
    CHECK (base_type IN ('INITIAL_BASELINE', 'APPROVED_RELEASE', 'RESTORED_RELEASE', 'EMPTY_INITIAL')),
    UNIQUE (stream_id, round_number)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS v03_collaboration_rounds_one_active_idx
    ON v03_collaboration_rounds(stream_id) WHERE status = 'ACTIVE'`,
  `CREATE TABLE IF NOT EXISTS v03_collaboration_revision_events (
    id TEXT PRIMARY KEY,
    stream_id TEXT NOT NULL REFERENCES v03_collaboration_streams(id),
    round_id TEXT NOT NULL REFERENCES v03_collaboration_rounds(id),
    annotation_id TEXT NOT NULL REFERENCES annotations(id),
    change_set_id TEXT NOT NULL,
    base_revision INTEGER NOT NULL,
    applied_revision INTEGER NOT NULL,
    target_key TEXT NOT NULL,
    target_label TEXT NOT NULL DEFAULT '',
    value_type TEXT NOT NULL,
    before_value_json JSONB NOT NULL,
    after_value_json JSONB NOT NULL,
    reason TEXT,
    actor_email TEXT NOT NULL,
    actor_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (value_type IN ('TEXT', 'SINGLE_SELECT', 'MULTI_SELECT', 'STRUCTURE'))
  )`,
  `CREATE INDEX IF NOT EXISTS v03_collaboration_revision_events_round_idx
    ON v03_collaboration_revision_events(round_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS v03_collaboration_revision_events_target_idx
    ON v03_collaboration_revision_events(stream_id, target_key, created_at)`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS collaboration_round_id TEXT REFERENCES v03_collaboration_rounds(id)`,
  `ALTER TABLE analysis_comments ADD COLUMN IF NOT EXISTS base_working_revision INTEGER`,
  `ALTER TABLE approved_analysis_releases ADD COLUMN IF NOT EXISTS collaboration_stream_id TEXT REFERENCES v03_collaboration_streams(id)`,
  `ALTER TABLE approved_analysis_releases ADD COLUMN IF NOT EXISTS collaboration_round_id TEXT REFERENCES v03_collaboration_rounds(id)`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    wecom_corp_id TEXT NOT NULL,
    wecom_user_id TEXT NOT NULL,
    identity_key TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    avatar_url TEXT,
    email TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    last_login_at TEXT NOT NULL,
    last_synced_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (wecom_corp_id, wecom_user_id),
    CHECK (status IN ('ACTIVE', 'DISABLED'))
  )`,
  `CREATE TABLE IF NOT EXISTS user_departments (
    user_id TEXT NOT NULL REFERENCES users(id),
    wecom_department_id TEXT NOT NULL,
    department_name TEXT NOT NULL,
    is_primary INTEGER NOT NULL DEFAULT 0,
    synced_at TEXT NOT NULL,
    PRIMARY KEY (user_id, wecom_department_id)
  )`,
  `CREATE TABLE IF NOT EXISTS auth_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    revoked_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS auth_sessions_expires_at_idx ON auth_sessions(expires_at)`,
  `CREATE TABLE IF NOT EXISTS oauth_states (
    id TEXT PRIMARY KEY,
    state_hash TEXT NOT NULL UNIQUE,
    browser_nonce_hash TEXT NOT NULL,
    return_to TEXT NOT NULL DEFAULT '/',
    flow_type TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT,
    created_at TEXT NOT NULL,
    CHECK (flow_type IN ('QR', 'IN_APP'))
  )`,
  `CREATE INDEX IF NOT EXISTS oauth_states_expires_at_idx ON oauth_states(expires_at)`,
  `CREATE TABLE IF NOT EXISTS wecom_app_tokens (
    corp_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    token_ciphertext TEXT NOT NULL,
    token_iv TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (corp_id, agent_id)
  )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    actor_email TEXT NOT NULL,
    action TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_id TEXT NOT NULL,
    detail_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS audit_logs_object_idx ON audit_logs(object_type, object_id)`,
  // Supabase also exposes the public schema over PostgREST. Runtime access only
  // happens server-side through the BYPASSRLS pooler role, so RLS with no
  // policies closes the anon/authenticated path without affecting any query.
  // Keep this list covering every table above — a table added without RLS is a
  // publicly readable table.
  `ALTER TABLE app_admins ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE videos ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE annotations ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE annotation_taxonomy_versions ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE shot_groups ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE shots ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE field_answers ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE annotation_creative_structures ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE annotation_snapshots ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE assignment_reviews ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE assignment_review_snapshots ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE analysis_comments ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE analysis_revision_suggestions ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE analysis_review_rounds ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE analysis_revision_events ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE approved_analysis_releases ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE users ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE user_departments ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE auth_sessions ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE oauth_states ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE wecom_app_tokens ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE v03_collaboration_streams ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE v03_collaboration_sources ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE v03_collaboration_baselines ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE v03_collaboration_rounds ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE v03_collaboration_revision_events ENABLE ROW LEVEL SECURITY`,
  `DO $$
  BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
      REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
      REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
    END IF;
  END
  $$`,
];

export async function applySchema() {
  const db = getDbClient();
  await db.batch(statements.map((statement) => db.prepare(statement)));
}
